import { useAuth } from "@/_core/hooks/useAuth";
import DashboardShell from "@/components/DashboardShell";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Car, ClipboardCheck, CreditCard, Gauge, Wrench } from "lucide-react";

function Metric({ label, value, detail, tone = "light" }: { label: string; value: number; detail: string; tone?: "light" | "dark" | "gold" }) {
  const className = tone === "dark" ? "bg-black text-white" : tone === "gold" ? "border-[#cfad58] bg-[#fbf4df] text-black" : "border-gray-200 bg-white text-black";
  return <article className={`border p-5 ${className}`}><p className={`text-[10px] font-bold uppercase tracking-[0.14em] ${tone === "dark" ? "text-white/55" : "text-gray-500"}`}>{label}</p><p className="mt-2 text-3xl font-bold" style={{ fontFamily: "var(--font-display)" }}>{value}</p><p className={`mt-1 text-[11px] leading-4 ${tone === "dark" ? "text-white/60" : "text-gray-500"}`}>{detail}</p></article>;
}

function formatDate(value: Date | string) {
  return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

export default function CommandCenter() {
  const { user } = useAuth();
  const summary = trpc.operations.commandCenter.useQuery(undefined, { enabled: user?.role === "admin", refetchOnWindowFocus: false });

  if (user?.role !== "admin") {
    return <DashboardShell title="Command Center"><section className="border border-gray-200 bg-white p-8 text-center"><AlertTriangle className="mx-auto text-gray-300" size={28} /><h2 className="mt-3 text-xl font-bold text-black" style={{ fontFamily: "var(--font-display)" }}>Administrator access required</h2><p className="mt-2 text-sm text-gray-500">This operating view is available only to authorized DreamCarz administrators.</p></section></DashboardShell>;
  }

  const data = summary.data;
  return <DashboardShell title="Command Center">
    <div className="mx-auto max-w-6xl space-y-6">
      <header className="border-b border-gray-200 pb-6"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#a8832d]">DreamCarz operating intelligence</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-[-0.04em] text-black" style={{ fontFamily: "var(--font-display)" }}>Command Center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-600">A live view of recorded fleet readiness, transaction state, service workload, and exceptions. Metrics reflect stored operating records only; they are not forecasts or financial projections.</p></div><button type="button" onClick={() => summary.refetch()} disabled={summary.isFetching} className="h-10 border border-black px-4 text-xs font-bold text-black disabled:opacity-50">{summary.isFetching ? "Refreshing…" : "Refresh live records"}</button></div></header>

      {summary.isLoading && <p className="py-12 text-center text-sm text-gray-500">Loading actual DreamCarz operating records…</p>}
      {summary.error && <p className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{summary.error.message}</p>}
      {data && <>
        <section className="grid gap-px border border-gray-200 bg-gray-200 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Fleet recorded" value={data.fleet.total} detail={`${data.fleet.available} marked available`} /><Metric label="Active rentals" value={data.transactions.activeRentals} detail="Recorded active transaction state" tone="dark" /><Metric label="Manual exceptions" value={data.transactions.manualExceptions} detail="Transactions requiring operations review" tone="gold" /><Metric label="Payment pending" value={data.transactions.pendingPayments} detail="Gateway status has not been recorded as complete" /></section>
        <section className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><div className="border border-gray-200 bg-white p-5"><div className="flex items-center gap-2"><Gauge size={17} className="text-[#a8832d]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-gray-500">Fleet readiness</p><h2 className="mt-1 text-lg font-bold text-black">Vehicle operating posture</h2></div></div><div className="mt-5 grid gap-px border border-gray-200 bg-gray-200 sm:grid-cols-3"><Metric label="Available" value={data.fleet.available} detail="Passports marked ready" /><Metric label="In active use" value={data.fleet.activeRental} detail="Passports marked active rental" /><Metric label="Needs attention" value={data.fleet.requiresAttention} detail="Inspection, maintenance, or service status" tone="gold" /></div><p className="mt-4 text-[11px] leading-5 text-gray-500">Vehicle Passport information is maintained by authorized operations staff. An empty value means no Passport record has been created—not that a vehicle is available.</p></div><div className="border border-gray-200 bg-[#faf9f6] p-5"><div className="flex items-center gap-2"><AlertTriangle size={17} className="text-[#a8832d]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-gray-500">Operational attention</p><h2 className="mt-1 text-lg font-bold text-black">Priority queue</h2></div></div><div className="mt-5 space-y-3"><div className="flex items-center justify-between border-b border-gray-200 pb-3 text-sm"><span className="flex items-center gap-2 text-gray-600"><AlertTriangle size={14} />Open incidents</span><strong>{data.operations.openIncidents}</strong></div><div className="flex items-center justify-between border-b border-gray-200 pb-3 text-sm"><span className="flex items-center gap-2 text-gray-600"><Wrench size={14} />Open maintenance</span><strong>{data.operations.openMaintenance}</strong></div><div className="flex items-center justify-between border-b border-gray-200 pb-3 text-sm"><span className="flex items-center gap-2 text-gray-600"><ClipboardCheck size={14} />Inspection work</span><strong>{data.operations.pendingInspections}</strong></div><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-gray-600"><Car size={14} />Scheduled handoffs</span><strong>{data.operations.scheduledHandoffs}</strong></div></div></div></section>
        <section className="border border-gray-200 bg-white p-5"><div className="flex items-center gap-2"><CreditCard size={17} className="text-[#a8832d]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-gray-500">Transaction activity</p><h2 className="mt-1 text-lg font-bold text-black">Most recently updated records</h2></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-[760px] w-full text-left"><thead className="border-y border-gray-200 bg-[#f7f5f0]"><tr className="text-[10px] uppercase tracking-wider text-gray-500"><th className="px-3 py-3">Reference</th><th className="px-3 py-3">Vehicle</th><th className="px-3 py-3">Type</th><th className="px-3 py-3">Lifecycle</th><th className="px-3 py-3">Payment</th><th className="px-3 py-3">Updated</th></tr></thead><tbody>{data.recentTransactions.map(item => <tr key={item.id} className="border-b border-gray-100 text-[12px]"><td className="px-3 py-3 font-semibold text-black">{item.reference}</td><td className="px-3 py-3 text-gray-700">{item.vehicleName}</td><td className="px-3 py-3 capitalize text-gray-600">{item.transactionType}</td><td className="px-3 py-3 capitalize text-gray-600">{item.status.replaceAll("_", " ")}</td><td className="px-3 py-3 capitalize text-gray-600">{item.paymentStatus.replaceAll("_", " ")}</td><td className="px-3 py-3 text-gray-500">{formatDate(item.updatedAt)}</td></tr>)}{!data.recentTransactions.length && <tr><td colSpan={6} className="px-3 py-8 text-center text-sm text-gray-400">No rental or purchase transaction records have been created yet.</td></tr>}</tbody></table></div></section>
      </>}
    </div>
  </DashboardShell>;
}
