CREATE TABLE `rental_application_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`userId` int NOT NULL,
	`documentType` enum('license_front','license_back','live_selfie') NOT NULL,
	`storageKey` varchar(512) NOT NULL,
	`originalFilename` varchar(255) NOT NULL,
	`contentType` varchar(128) NOT NULL,
	`reviewStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rental_application_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rental_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`status` enum('not_started','in_progress','submitted','under_review','approved','needs_attention','declined') NOT NULL DEFAULT 'not_started',
	`currentStep` int NOT NULL DEFAULT 1,
	`phone` varchar(32),
	`addressLine1` varchar(255),
	`city` varchar(100),
	`state` varchar(64),
	`postalCode` varchar(24),
	`dateOfBirth` varchar(10),
	`licenseState` varchar(64),
	`licenseClass` varchar(24),
	`licenseExpiresOn` varchar(10),
	`drivingExperience` varchar(32),
	`recentClaims` varchar(32),
	`preferredVehicleClasses` text,
	`rentalPurpose` varchar(64),
	`pickupLocation` varchar(255),
	`requestedStartDate` varchar(10),
	`requestedEndDate` varchar(10),
	`identityVerificationStatus` enum('not_started','documents_uploaded','pending_review','verified','manual_review','failed') NOT NULL DEFAULT 'not_started',
	`verificationProvider` varchar(64),
	`identityConsentAt` timestamp,
	`rentalTermsConsentAt` timestamp,
	`submittedAt` timestamp,
	`reviewedAt` timestamp,
	`reviewNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rental_applications_id` PRIMARY KEY(`id`),
	CONSTRAINT `rental_applications_userId_unique` UNIQUE(`userId`)
);
