CREATE TABLE `reservation_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`reference` varchar(24) NOT NULL,
	`vehicleId` int NOT NULL,
	`vehicleName` varchar(160) NOT NULL,
	`vehicleCategory` varchar(48) NOT NULL,
	`vehicleImage` varchar(512) NOT NULL,
	`memberTier` enum('freedom','plus','pro','elite') NOT NULL,
	`estimatedWeeklyFee` int NOT NULL,
	`requestedStartDate` varchar(10) NOT NULL,
	`requestedEndDate` varchar(10) NOT NULL,
	`pickupLocation` varchar(255) NOT NULL,
	`dropoffLocation` varchar(255),
	`contactPhone` varchar(32) NOT NULL,
	`notes` text,
	`status` enum('submitted','under_review','confirmed','change_requested','canceled','declined') NOT NULL DEFAULT 'submitted',
	`reviewNote` text,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reservation_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `reservation_requests_reference_unique` UNIQUE(`reference`)
);
