CREATE TABLE `customer_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fullName` varchar(160),
	`email` varchar(320),
	`phone` varchar(32),
	`phoneVerifiedAt` timestamp,
	`emailVerifiedAt` timestamp,
	`addressLine1` varchar(255),
	`addressLine2` varchar(255),
	`city` varchar(100),
	`state` varchar(64),
	`postalCode` varchar(24),
	`dateOfBirth` varchar(10),
	`identityStatus` enum('not_started','pending','verified','requires_input','manual_review','redacted') NOT NULL DEFAULT 'not_started',
	`licenseStatus` enum('not_started','pending','verified','expired','manual_review','failed') NOT NULL DEFAULT 'not_started',
	`identityProvider` varchar(64),
	`identityProviderSessionId` varchar(160),
	`identityVerifiedAt` timestamp,
	`licenseVerifiedAt` timestamp,
	`verificationExpiresAt` timestamp,
	`profileStatus` enum('incomplete','ready_for_verification','verified','manual_review','restricted') NOT NULL DEFAULT 'incomplete',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customer_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `customer_profiles_userId_unique` UNIQUE(`userId`)
);
