import { useAuth } from "@/_core/hooks/useAuth";
import Footer from "@/components/Footer";
import { HomeConcierge } from "@/components/HomeConcierge";
import Navigation from "@/components/Navigation";
import { ArrowRight, BadgeCheck, Car, CircleDollarSign, Gift, Headphones, MapPin, ShieldCheck, Sparkles, Star, Users } from "lucide-react";
import { Link } from "wouter";

const currentInventory = [
  { id: "2024-chevrolet-malibu-gray", year: "2024", make: "Chevrolet", model: "Malibu", color: "Gray", category: "Sedan", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/ogLykrxMFWpmsTbU.png" },
  { id: "2022-chevrolet-traverse-white", year: "2022", make: "Chevrolet", model: "Traverse", color: "White", category: "SUV", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/uLwJSHBxRyWslZQQ.png" },
  { id: "2024-ford-fusion-gray", year: "2024", make: "Ford", model: "Fusion", color: "Gray", category: "Sedan", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/qRKjtXjkrFUfxMqh.png" },
  { id: "2020-chevrolet-traverse-gray", year: "2020", make: "Chevrolet", model: "Traverse", color: "Gray", category: "SUV", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/mFFrLJBzyJWqricP.png" },
  { id: "2019-chevrolet-malibu-black", year: "2019", make: "Chevrolet", model: "Malibu", color: "Black", category: "Sedan", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/njSpzrWxcQZbiWBb.png" },
  { id: "2015-ford-taurus-gray", year: "2015", make: "Ford", model: "Taurus", color: "Gray", category: "Sedan", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/BDcxxQLQxENUVvqj.png" },
  { id: "2020-chevrolet-equinox-gray", year: "2020", make: "Chevrolet", model: "Equinox", color: "Gray", category: "SUV", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/QuCANehFYgQjJKfm.png" },
  { id: "2020-chevrolet-equinox-black", year: "2020", make: "Chevrolet", model: "Equinox", color: "Black", category: "SUV", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/TAiKEadRDaSWeYcf.png" },
] as const;

const choices = [
  { icon: Car, eyebrow: "Rent", title: "Rent a vehicle", description: "Start with a personal concierge path, then choose the confirmed vehicle that fits your schedule.", cta: "Start rental path", href: "/concierge?intent=rental", image: currentInventory[1].image },
  { icon: CircleDollarSign, eyebrow: "Buy", title: "Buy a vehicle", description: "Start a concierge purchase path, then choose the confirmed vehicle that interests you.", cta: "Start purchase path", href: "/concierge?intent=purchase", image: currentInventory[4].image },
  { icon: Star, eyebrow: "DreamCarz membership", title: "Unlock your path", description: "Compare membership enrollment and monthly costs separately from vehicle access.", cta: "Explore pricing", href: "/pricing", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/gyIfJAbATfYnyeYI.png" },
] as const;
const benefits = [
  { icon: BadgeCheck, title: "Confirmed inventory", detail: "Current vehicles shown clearly." },
  { icon: CircleDollarSign, title: "Rent or Buy", detail: "Flexible paths for every reason to drive." },
  { icon: Sparkles, title: "Member benefits", detail: "Clear programs. Clear next steps." },
  { icon: Gift, title: "Clear next steps", detail: "From your first click onward." },
] as const;
const support = [
  { icon: Car, title: "Request a vehicle", detail: "Open a vehicle request and we will find the right next step for you.", href: "/fleet" },
  { icon: ShieldCheck, title: "Protection & support", detail: "Clear next steps and documented review.", href: "/dashboard/report-issue" },
  { icon: MapPin, title: "Locations & partners", detail: "Find DreamCarz locations and reference services.", href: "/dashboard/locations" },
  { icon: Headphones, title: "Transparent & simple", detail: "No hidden assumptions. Clear reviews.", href: "/contact" },
] as const;
const experienceSteps = [
  ["01", "Ask", "Tell DreamCarz what you need today."],
  ["02", "Direct", "Choose a rental, purchase, or membership path."],
  ["03", "Compare", "See confirmed vehicles and membership context together."],
  ["04", "Understand", "Learn how DCP may apply under program rules."],
  ["05", "Act", "Save your path and continue when you are ready."],
] as const;
const dcpSteps = [
  ["01", "Qualify", "Transportation activity may be considered under the applicable program rules."],
  ["02", "Verify", "DreamCarz reviews eligible activity before it is recorded."],
  ["03", "Build DCP", "Your account can track eligible DCP under the program rules."],
  ["04", "Use when eligible", "Redemption limits, verification, and eligibility requirements apply."],
] as const;

export default function Home() {
  return <div className="min-h-screen bg-white text-black">
    <Navigation />
    <main>
      <section className="border-b border-[#ebe7df] bg-[#fbfaf7] px-5 pt-16 sm:px-8 lg:px-10 lg:pt-20">
        <div className="mx-auto grid max-w-7xl grid-cols-1 overflow-hidden border border-[#eee9df] bg-white lg:grid-cols-[0.86fr_1.14fr]">
          <div className="flex min-h-[455px] flex-col justify-center px-7 py-12 sm:px-11 lg:min-h-[515px] lg:px-12"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#b08b35]">Your transportation path starts here</p><h1 className="mt-4 max-w-md font-display text-5xl font-bold leading-[0.91] tracking-[-0.06em] sm:text-6xl lg:text-7xl">Drive what<br />moves you.</h1><p className="mt-5 max-w-md text-sm leading-relaxed text-gray-600 sm:text-base">Find the right way to drive today, then build a clearer path for tomorrow. DreamCarz helps you rent, buy, compare membership, and explore confirmed vehicles.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/concierge?intent=rental" className="inline-flex h-11 items-center gap-2 rounded-full bg-black px-5 text-sm font-semibold text-white transition-transform active:scale-[0.97]">Start renting <ArrowRight size={15} /></Link><Link href="/concierge?intent=purchase" className="inline-flex h-11 items-center gap-2 rounded-full border border-black px-5 text-sm font-semibold text-black transition-colors hover:bg-black hover:text-white">Start buying <ArrowRight size={15} /></Link></div><Link href="/concierge" className="mt-5 inline-flex w-fit items-center gap-2 text-sm font-semibold text-[#a5802a] underline underline-offset-4">What do you need today? <ArrowRight size={14} /></Link></div>
          <div className="relative flex min-h-[365px] items-center justify-center overflow-hidden bg-[#f4f0e8] lg:min-h-[515px]"><div className="absolute inset-x-12 top-10 h-36 border border-[#d6b85f]/40 sm:inset-x-16" /><img src="https://files.manuscdn.com/user_upload_by_module/session_file/310419663031545745/gyIfJAbATfYnyeYI.png" alt="White Tesla Model 3 in a DreamCarz studio setting" className="relative z-10 h-full min-h-[365px] w-full object-cover lg:min-h-[515px]" /></div>
        </div>
        <HomeConcierge />
        <div className="mx-auto max-w-7xl pb-7"><div className="grid overflow-hidden border border-[#e7e1d7] bg-white md:grid-cols-4">{benefits.map((benefit, index) => { const Icon = benefit.icon; return <div key={benefit.title} className={`flex gap-3 p-4 ${index < benefits.length - 1 ? "border-b border-[#e7e1d7] md:border-b-0 md:border-r" : ""}`}><Icon className="mt-0.5 shrink-0 text-[#b08b35]" size={18} /><div><p className="text-xs font-bold">{benefit.title}</p><p className="mt-1 text-[11px] leading-relaxed text-gray-500">{benefit.detail}</p></div></div>; })}</div></div>
      </section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#b08b35]">What do you need today?</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-0.05em] sm:text-5xl">Choose a clear next move.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-relaxed text-gray-500">Ask naturally. DreamCarz guides your path, shows confirmed vehicles, and keeps qualifications and final terms clear.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{choices.map((choice) => { const Icon = choice.icon; return <article key={choice.title} className="overflow-hidden border border-gray-200 bg-white"><div className="h-44 overflow-hidden bg-[#f2eee6]"><img src={choice.image} alt="" className="h-full w-full object-cover transition-transform duration-300 hover:scale-105" /></div><div className="relative p-6"><span className="absolute -top-5 grid h-10 w-10 place-items-center rounded-full bg-black text-white"><Icon size={17} /></span><p className="pt-2 text-[10px] font-bold uppercase tracking-[0.18em] text-[#b08b35]">{choice.eyebrow}</p><h3 className="mt-2 font-display text-2xl font-bold tracking-[-0.04em]">{choice.title}</h3><p className="mt-3 min-h-[66px] text-sm leading-relaxed text-gray-500">{choice.description}</p><Link href={choice.href} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold underline underline-offset-4">{choice.cta} <ArrowRight size={14} /></Link></div></article>; })}</div></section>
      <section className="border-y border-[#ece7de] bg-[#fbfaf7] px-5 py-12 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#b08b35]">A focused way forward</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-0.05em] sm:text-4xl">From question to next step.</h2></div><Link href="/concierge" className="inline-flex items-center gap-2 text-sm font-semibold underline underline-offset-4">Ask DreamCarz <ArrowRight size={14} /></Link></div><div className="mt-8 grid divide-y divide-[#e5ded2] border-y border-[#e5ded2] sm:grid-cols-5 sm:divide-x sm:divide-y-0">{experienceSteps.map(([number, title, copy]) => <div key={number} className="min-h-[138px] p-5"><p className="text-[10px] font-bold tracking-[0.16em] text-[#b08b35]">{number}</p><h3 className="mt-5 text-sm font-bold">{title}</h3><p className="mt-2 text-xs leading-relaxed text-gray-500">{copy}</p></div>)}</div></div></section>
      <section className="border-y border-[#ece7de] bg-[#fbfaf7] px-5 py-16 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#b08b35]">Available now</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-0.05em] sm:text-5xl">Featured vehicles.</h2></div><p className="max-w-sm text-sm leading-relaxed text-gray-500">Your confirmed DreamCarz inventory. Open any vehicle to view it full-screen, then rent or buy.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{currentInventory.slice(0, 4).map((vehicle) => <Link key={vehicle.id} href={`/vehicle?id=${vehicle.id}`} className="group overflow-hidden border border-[#e6e1d9] bg-white transition-shadow hover:shadow-[0_14px_28px_rgba(0,0,0,0.07)]"><div className="relative flex h-48 items-center justify-center overflow-hidden bg-[#f4f1eb]"><span className="absolute left-3 top-3 z-10 rounded-full bg-white px-2 py-1 text-[9px] font-bold uppercase tracking-[0.13em] text-black">Confirmed</span><img src={vehicle.image} alt={`${vehicle.year} ${vehicle.make} ${vehicle.model} in ${vehicle.color}`} className="h-full w-full object-contain transition-transform duration-300 group-hover:scale-105" /></div><div className="p-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#b08b35]">{vehicle.category}</p><h3 className="mt-2 font-display text-xl font-bold tracking-[-0.04em]">{vehicle.year} {vehicle.make}<br />{vehicle.model}</h3><div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-3 text-xs font-semibold"><span>Rent or buy</span><span className="grid h-6 w-6 place-items-center rounded-full border border-gray-300"><ArrowRight size={13} /></span></div></div></Link>)}</div><div className="mt-8 text-center"><Link href="/fleet" className="inline-flex h-11 items-center gap-2 rounded-full bg-black px-6 text-sm font-semibold text-white">View all inventory <ArrowRight size={15} /></Link></div></div></section>
      <section className="bg-black px-5 py-12 text-white sm:px-8 lg:px-10 lg:py-14"><div className="mx-auto grid max-w-7xl gap-9 lg:grid-cols-[0.88fr_0.72fr_1.4fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#cfac52]">Membership value in context</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-0.05em] sm:text-5xl">See more than the vehicle.</h2><p className="mt-4 max-w-sm text-sm leading-relaxed text-gray-300">Membership helps make vehicle access, program value, and next steps visible before you submit a request. Vehicle-specific amounts are reviewed separately.</p><Link href="/pricing" className="mt-7 inline-flex h-11 items-center gap-2 rounded-full bg-[#d1ad54] px-5 text-sm font-semibold text-black">Compare membership paths <ArrowRight size={15} /></Link></div><div className="hidden h-56 overflow-hidden lg:block"><img src={currentInventory[7].image} alt="Black Chevrolet Equinox" className="h-full w-full object-contain" /></div><div className="grid gap-5 sm:grid-cols-2"><div><CircleDollarSign className="text-[#d1ad54]" size={20} /><h3 className="mt-3 text-sm font-bold">Clear comparison</h3><p className="mt-2 text-xs leading-relaxed text-gray-400">Keep membership context and vehicle terms visible as separate decisions.</p></div><div><Users className="text-[#d1ad54]" size={20} /><h3 className="mt-3 text-sm font-bold">Program guidance</h3><p className="mt-2 text-xs leading-relaxed text-gray-400">See which program path fits your current transportation need.</p></div><div><Sparkles className="text-[#d1ad54]" size={20} /><h3 className="mt-3 text-sm font-bold">DCP context</h3><p className="mt-2 text-xs leading-relaxed text-gray-400">Understand eligible DCP under verification and redemption rules.</p></div><div><ShieldCheck className="text-[#d1ad54]" size={20} /><h3 className="mt-3 text-sm font-bold">Reviewed terms</h3><p className="mt-2 text-xs leading-relaxed text-gray-400">Availability, eligibility, and final terms are confirmed before moving forward.</p></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[0.82fr_1.18fr] lg:items-start"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#b08b35]">DCP program value</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-0.05em]">Build toward tomorrow with clear rules today.</h2><p className="mt-4 max-w-md text-sm leading-relaxed text-gray-500">DCP is not cash. It is a program record that may be earned and used only when the applicable eligibility, verification, and redemption rules are met.</p><Link href="/membership" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold underline underline-offset-4">Learn about membership value <ArrowRight size={14} /></Link></div><div className="grid border-y border-[#e7e1d7] sm:grid-cols-2">{dcpSteps.map(([number, title, copy]) => <div key={number} className="min-h-[152px] border-b border-[#e7e1d7] p-5 even:sm:border-l sm:nth-[n+3]:border-b-0"><p className="text-[10px] font-bold tracking-[0.16em] text-[#b08b35]">{number}</p><h3 className="mt-4 text-sm font-bold">{title}</h3><p className="mt-2 text-xs leading-relaxed text-gray-500">{copy}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#b08b35]">Not sure where to start?</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-0.05em]">We are here to help.</h2><p className="mt-4 max-w-sm text-sm leading-relaxed text-gray-500">Start a personal conversation, compare confirmed visual vehicle cards, and choose the path that fits you.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/concierge" className="inline-flex h-11 items-center gap-2 rounded-full bg-black px-5 text-sm font-semibold text-white">Ask DreamCarz <ArrowRight size={15} /></Link><Link href="/contact" className="inline-flex h-11 items-center gap-2 rounded-full border border-black px-5 text-sm font-semibold text-black">Talk to our team <ArrowRight size={15} /></Link></div></div><div className="grid gap-3 sm:grid-cols-2">{support.map((item) => { const Icon = item.icon; return <Link key={item.title} href={item.href} className="group border border-[#e8e3da] p-5 transition-colors hover:border-black"><Icon className="text-[#b08b35]" size={20} /><h3 className="mt-5 text-sm font-bold">{item.title}</h3><p className="mt-2 text-xs leading-relaxed text-gray-500">{item.detail}</p><ArrowRight className="mt-5 transition-transform group-hover:translate-x-1" size={16} /></Link>; })}</div></div></section>
    </main>
    <Footer />
  </div>;
}
