import { Link } from "wouter";
import { ArrowRight, Building2, Car, CheckCircle2, FileText, ShieldCheck, Users } from "lucide-react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const paths = [
  { icon: Car, kicker: "Drive", title: "Member", statement: "I want a better way to drive.", description: "Create an account, choose an eligible membership experience, complete rental readiness, and manage reservations and transportation activity in one place.", href: "/membership", cta: "Explore membership" },
  { icon: Users, kicker: "Build", title: "Associate", statement: "I want to help build customers.", description: "Share approved information, support verified customer activity, and follow the official qualification and recognition rules for the Associate pathway.", href: "/login", cta: "Create an account" },
  { icon: Building2, kicker: "Participate", title: "Fleet Partner", statement: "I want to support fleet growth.", description: "Explore fleet opportunities that are governed by defined operating standards, disclosures, participation terms, and written agreements.", href: "/contact", cta: "Speak with the team" },
];

export default function Opportunity() {
  return <div className="min-h-screen bg-white text-black"><Navigation /><main>
    <section className="bg-[#f7f5f0] px-6 pb-20 pt-32 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#a8832d]">DreamCarz pathways</p><div className="mt-6 grid grid-cols-1 gap-10 lg:grid-cols-[0.95fr_1.05fr]"><div><h1 className="font-display text-5xl font-bold leading-[0.94] tracking-[-0.055em] md:text-7xl">One brand.<br />Three ways in.</h1><p className="mt-6 max-w-xl text-base leading-relaxed text-gray-600">DreamCarz connects members, customer builders, and fleet participants through one transportation ecosystem. Choose the relationship that fits your objective.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-full bg-black px-6 py-3 text-sm font-semibold text-white">Create an account<ArrowRight size={15} /></Link><a href="#paths" className="rounded-full border border-black px-6 py-3 text-sm font-semibold">View the pathways</a></div></div><div className="flex min-h-[290px] items-center justify-center bg-[#ebe7de] p-6"><img src="/manus-storage/car-card-1_8dfc0a4a.png" alt="DreamCarz premium sports car" className="h-[265px] w-full object-contain" /></div></div></div></section>
    <section id="paths" className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="grid grid-cols-1 border-t border-gray-200 md:grid-cols-3">{paths.map(({ icon: Icon, kicker, title, statement, description, href, cta }) => <article key={title} className="border-b border-gray-200 py-8 md:border-b-0 md:border-r md:px-8 md:first:pl-0 md:last:border-r-0"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-black text-white"><Icon size={17} /></span><p className="mt-6 text-[11px] font-bold uppercase tracking-[0.18em] text-[#a8832d]">{kicker}</p><h2 className="mt-2 font-display text-4xl font-bold tracking-[-0.045em]">{title}</h2><p className="mt-4 text-lg leading-snug">“{statement}”</p><p className="mt-5 text-sm leading-relaxed text-gray-600">{description}</p><Link href={href} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold underline underline-offset-4">{cta}<ArrowRight size={14} /></Link></article>)}</div></section>
    <section className="bg-[#f7f5f0] px-6 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-12 lg:grid-cols-2"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#a8832d]">Associate process</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-0.045em]">Build customers. Create progress.</h2><p className="mt-5 max-w-lg text-sm leading-relaxed text-gray-600">The Associate pathway is customer-centered. Recognition, qualification, timing, and any compensation treatment are governed by the current official documentation.</p><p className="mt-6 text-sm font-semibold">Recruiting alone does not create recognized activity. Verified customer participation does.</p></div><div className="border-t border-[#d8d1c4]">{[["01", "Build", "Share approved DreamCarz information and support a transparent member experience."], ["02", "Recognize", "Qualifying customer activity may be recognized under the written program rules."], ["03", "Unlock", "As a participant qualifies, access and pathway opportunities can expand under the applicable terms."]].map(([number, title, description]) => <div key={number} className="grid grid-cols-[64px_1fr] border-b border-[#d8d1c4] py-6"><p className="font-display text-4xl text-[#a8832d]">{number}</p><div><h3 className="text-sm font-bold uppercase tracking-[0.14em]">{title}</h3><p className="mt-2 text-sm leading-relaxed text-gray-600">{description}</p></div></div>)}</div></div></section>
    <section id="fleet-partner" className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="grid grid-cols-1 gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#a8832d]">Fleet Partner process</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-0.045em]">Build the fleet with intent.</h2><p className="mt-5 text-sm leading-relaxed text-gray-600">Fleet participation should begin with clarity: the vehicle plan, operating standards, participation terms, and any renewal or exit mechanics must be defined before commitment.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-full bg-black px-5 py-3 text-sm font-semibold text-white">Talk with the team<ArrowRight size={14} /></Link></div><div className="grid grid-cols-1 divide-y divide-gray-200 border-y border-gray-200">{[[FileText, "Vehicle plan", "Document the vehicle model, ownership or operating approach, and availability process."], [ShieldCheck, "Operating standards", "Set expectations for maintenance, insurance, safety, customer care, and platform requirements."], [CheckCircle2, "Participation terms", "Document roles, responsibilities, disclosures, risk allocations, and economics in writing."], [Building2, "Cycle mechanics", "Address renewal, exit, reinvestment, or other end-of-cycle choices through the agreement."]].map(([Icon, title, description]) => { const FeatureIcon = Icon as typeof FileText; return <div key={title as string} className="flex gap-4 py-5"><FeatureIcon size={19} className="mt-0.5 shrink-0 text-[#a8832d]" /><div><h3 className="font-semibold">{title as string}</h3><p className="mt-1 text-sm leading-relaxed text-gray-600">{description as string}</p></div></div>; })}</div></div></section>
    <section className="border-t border-gray-200 px-6 py-20 lg:px-10"><div className="mx-auto max-w-3xl text-center"><h2 className="font-display text-4xl font-bold tracking-[-0.045em]">Choose the relationship that fits your objective.</h2><p className="mt-4 text-sm leading-relaxed text-gray-500">Membership, Associate, and Fleet Partner pathways have different responsibilities. Final eligibility, participation, compensation, vehicle, and program terms are governed by the applicable agreements and official documentation.</p><Link href="/login" className="mt-8 inline-flex items-center gap-2 rounded-full bg-black px-6 py-3 text-sm font-semibold text-white">Create your DreamCarz account<ArrowRight size={14} /></Link></div></section>
  </main><Footer /></div>;
}
