import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ShieldCheck, Users } from "lucide-react";
import { useMemo, useState } from "react";

const assignableRoles = ["customer", "associate", "fleet_partner", "operations", "support", "manager", "administrator"] as const;
const label = (role: string) => role.replaceAll("_", " ");

export function AdministratorUserRoleManager() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(1);
  const [selectedUserId, setSelectedUserId] = useState<number | null>(null);
  const [role, setRole] = useState<(typeof assignableRoles)[number]>("operations");
  const input = useMemo(() => ({ query: query.trim() || undefined, page, pageSize: 10 }), [page, query]);
  const directory = trpc.roles.directory.useQuery(input, { enabled: user?.role === "admin", refetchOnWindowFocus: false });
  const refresh = () => void utils.roles.directory.invalidate();
  const assign = trpc.roles.assign.useMutation({ onSuccess: refresh });
  const revoke = trpc.roles.revoke.useMutation({ onSuccess: refresh });
  const rows = directory.data?.items ?? [];
  const selected = rows.find(item => item.id === selectedUserId) ?? null;
  const totalPages = Math.max(1, Math.ceil((directory.data?.total ?? 0) / 10));

  return <section id="admin-roles" className="scroll-mt-6 border border-[#ded8cf] bg-[#faf9f6] p-5 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#B8860B]">Configuration</p><h3 className="mt-1 text-lg font-bold text-black">Users & roles</h3><p className="mt-1 max-w-3xl text-[12px] leading-5 text-gray-500">Grant and revoke operational access from verified DreamCarz accounts. Passwords, payment data, and private documents are never displayed here.</p></div><span className="inline-flex items-center gap-2 border border-[#d9d2c7] bg-white px-3 py-2 text-[10px] font-semibold text-gray-700"><ShieldCheck size={14} className="text-[#B8860B]" /> Audited changes</span></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]"><div><div className="flex flex-wrap items-center justify-between gap-3"><label className="min-w-0 flex-1 text-[11px] font-semibold text-gray-600">Find an account<input value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} placeholder="Name, email, or role" className="mt-1 h-10 w-full border border-gray-300 bg-white px-3 text-sm font-normal text-black outline-none focus:border-black" /></label><p className="pt-4 text-[11px] text-gray-500">{directory.data?.total ?? 0} accounts</p></div><div className="mt-4 overflow-x-auto border border-gray-200 bg-white"><table className="w-full min-w-[650px] text-left"><thead className="border-b border-gray-200 bg-[#fbfaf7]"><tr className="text-[10px] font-bold uppercase tracking-wide text-gray-500"><th className="p-3">Account</th><th className="p-3">Current roles</th><th className="p-3">Last sign-in</th><th className="p-3">Review</th></tr></thead><tbody>{rows.map(item => <tr key={item.id} className="border-b border-gray-100 last:border-0"><td className="p-3"><p className="text-xs font-semibold text-black">{item.name || "Unnamed account"}</p><p className="mt-1 text-[10px] text-gray-500">{item.email || "No email recorded"}</p></td><td className="p-3"><div className="flex flex-wrap gap-1">{item.roles.map(itemRole => <span key={itemRole} className="border border-[#ded8cf] bg-[#faf9f6] px-2 py-1 text-[9px] font-bold uppercase tracking-wide text-[#8f6e23]">{label(itemRole)}</span>)}</div></td><td className="p-3 text-[10px] text-gray-500">{item.lastSignedIn ? new Date(item.lastSignedIn).toLocaleDateString() : "Not recorded"}</td><td className="p-3"><button type="button" onClick={() => setSelectedUserId(item.id)} className="text-[10px] font-bold underline underline-offset-4">Manage</button></td></tr>)}{!directory.isLoading && !rows.length ? <tr><td colSpan={4} className="p-5 text-xs text-gray-500">No matching accounts.</td></tr> : null}</tbody></table></div><div className="mt-3 flex items-center justify-between"><button type="button" disabled={page <= 1} onClick={() => setPage(current => current - 1)} className="border border-gray-300 bg-white px-3 py-2 text-[10px] font-bold disabled:opacity-40">Previous</button><p className="text-[10px] text-gray-500">Page {page} of {totalPages}</p><button type="button" disabled={page >= totalPages} onClick={() => setPage(current => current + 1)} className="border border-gray-300 bg-white px-3 py-2 text-[10px] font-bold disabled:opacity-40">Next</button></div></div>
      <aside className="border border-[#ded8cf] bg-white p-4"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center bg-black text-[#d3a63f]"><Users size={15} /></span><div><p className="text-[10px] font-bold uppercase tracking-wide text-[#B8860B]">Role review</p><p className="text-xs font-bold text-black">{selected ? selected.name || selected.email || "Selected account" : "Select an account"}</p></div></div>{selected ? <><p className="mt-4 text-[11px] leading-5 text-gray-600">Choose an operational role to grant. Every change is recorded. You cannot revoke your own operational role.</p><label className="mt-4 block text-[11px] font-semibold text-gray-600">Role<select value={role} onChange={event => setRole(event.target.value as typeof role)} className="mt-1 h-10 w-full border border-gray-300 bg-white px-3 text-xs text-black outline-none focus:border-black">{assignableRoles.map(item => <option key={item} value={item}>{label(item)}</option>)}</select></label><button type="button" disabled={assign.isPending} onClick={() => assign.mutate({ userId: selected.id, role })} className="mt-3 h-10 w-full bg-black px-3 text-[11px] font-bold text-white disabled:opacity-50">{assign.isPending ? "Recording…" : `Grant ${label(role)}`}</button><div className="mt-5 border-t border-gray-200 pt-4"><p className="text-[10px] font-bold uppercase tracking-wide text-gray-500">Active operational roles</p><div className="mt-3 space-y-2">{selected.roles.map(itemRole => <div key={itemRole} className="flex items-center justify-between gap-2 border border-gray-200 p-2"><span className="text-[10px] font-bold capitalize text-black">{label(itemRole)}</span>{selected.id === user?.id ? <span className="text-[9px] text-gray-400">Current admin</span> : <button type="button" disabled={revoke.isPending} onClick={() => revoke.mutate({ userId: selected.id, role: itemRole as typeof role })} className="text-[9px] font-bold underline underline-offset-4 disabled:opacity-50">Revoke</button>}</div>)}</div></div>{assign.error || revoke.error ? <p className="mt-3 text-[11px] text-red-600">{assign.error?.message ?? revoke.error?.message}</p> : null}</> : <p className="mt-5 text-xs leading-5 text-gray-500">Choose an account to view its authorized roles. Customer credentials and private records remain unavailable.</p>}</aside></div>
  </section>;
}
