import { Search, UserRound, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";

function label(value: string | null) {
  return value ? value.replaceAll("_", " ") : "No transactions";
}

export function CustomerManagementPanel({ onReviewTransactions }: { onReviewTransactions: (query: string) => void }) {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const input = useMemo(() => ({ query: search.trim() || undefined, page, pageSize: 20 }), [search, page]);
  const customers = trpc.operations.customerDirectory.useQuery(input, { refetchOnWindowFocus: false });
  const records = customers.data?.items ?? [];
  const total = customers.data?.total ?? 0;
  const activeCustomers = customers.data?.activeJourneyCount ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / (customers.data?.pageSize ?? 20)));

  return <section className="mb-6 border border-[#ded8cf] bg-[#faf9f6] p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#B8860B]">Customer management</p><h3 className="mt-1 text-[16px] font-bold text-black">Customer directory</h3><p className="mt-1 max-w-3xl text-[12px] leading-5 text-gray-500">Account and transaction summaries for authorized administration. Credentials, payment details, and private documents are not listed here.</p></div><label className="flex h-10 items-center gap-2 border border-gray-200 bg-white px-3"><Search size={14} className="text-gray-400" /><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Find a customer" className="w-52 bg-transparent text-[12px] text-black outline-none" /></label></div>
    <div className="mt-5 grid gap-px overflow-hidden border border-gray-200 bg-gray-200 sm:grid-cols-3"><div className="bg-white p-4"><UsersRound size={15} className="text-[#B8860B]" /><p className="mt-3 text-2xl font-bold text-black">{total}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-gray-500">Customer accounts</p></div><div className="bg-white p-4"><UserRound size={15} className="text-[#B8860B]" /><p className="mt-3 text-2xl font-bold text-black">{activeCustomers}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-gray-500">Active journeys</p></div><div className="bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-gray-500">Directory status</p><p className="mt-4 text-[13px] font-semibold text-black">Account-owned</p><p className="mt-1 text-[10px] leading-4 text-gray-500">Page {page} of {totalPages} · Use the transaction console for controlled review.</p></div></div>
    <div className="mt-5 overflow-x-auto border border-gray-200 bg-white"><table className="min-w-[760px] w-full text-left"><thead className="border-b border-gray-200 bg-[#f4f1eb]"><tr className="text-[10px] uppercase tracking-wider text-gray-500"><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Journey summary</th><th className="px-3 py-3">Last activity</th><th className="px-3 py-3"></th></tr></thead><tbody>{records.map(record => <tr key={record.id} className="border-b border-gray-100 last:border-0 text-[11px] text-gray-600"><td className="px-3 py-3"><p className="font-semibold text-black">{record.name || "Customer"}</p><p className="mt-0.5 text-[10px] text-gray-500">{record.email || "No email recorded"}</p></td><td className="px-3 py-3"><p>{record.transactionCount} total · {record.openTransactionCount} open</p><p className="mt-0.5 text-[10px] uppercase tracking-wide text-gray-400">{label(record.latestTransactionType)} · {label(record.latestTransactionStatus)}</p></td><td className="px-3 py-3 text-[11px] text-gray-500">{record.latestTransactionUpdatedAt ? new Date(record.latestTransactionUpdatedAt).toLocaleDateString() : record.lastSignedIn ? new Date(record.lastSignedIn).toLocaleDateString() : "Not recorded"}</td><td className="px-3 py-3"><button type="button" onClick={() => onReviewTransactions(record.email || record.name || "")} className="text-[10px] font-bold text-black underline underline-offset-4">Review transactions</button></td></tr>)}{!customers.isLoading && !records.length && <tr><td colSpan={4} className="px-3 py-10 text-center text-[11px] text-gray-400">No customer accounts match this search.</td></tr>}</tbody></table></div>
    <div className="mt-4 flex items-center justify-between gap-3 text-[11px]"><p className="text-gray-500">Showing {records.length ? (page - 1) * (customers.data?.pageSize ?? 20) + 1 : 0}–{Math.min(page * (customers.data?.pageSize ?? 20), total)} of {total}</p><div className="flex gap-2"><button type="button" disabled={page === 1 || customers.isFetching} onClick={() => setPage(current => Math.max(1, current - 1))} className="border border-gray-300 px-3 py-2 font-semibold text-black disabled:opacity-40">Previous</button><button type="button" disabled={page >= totalPages || customers.isFetching} onClick={() => setPage(current => Math.min(totalPages, current + 1))} className="bg-black px-3 py-2 font-semibold text-white disabled:opacity-40">Next</button></div></div>
  </section>;
}
