import { useMemo, useState } from "react";
import { ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function EligibilityReviewControl({ reference, vehicleId, onRecorded }: { reference: string; vehicleId: string; onRecorded: () => void }) {
  const policies = trpc.operations.eligibilityPolicies.list.useQuery(undefined, { refetchOnWindowFocus: false });
  const [status, setStatus] = useState<"cleared" | "manual_review" | "unable_to_proceed">("manual_review");
  const [decisionReason, setDecisionReason] = useState("");
  const [eligibilityPolicyId, setEligibilityPolicyId] = useState("");
  const applicablePolicies = useMemo(() => (policies.data || []).filter(policy => policy.status === "active" && (policy.scope !== "specific_vehicle" || policy.vehicleId === vehicleId)), [policies.data, vehicleId]);
  const review = trpc.operations.reviewEligibility.useMutation({ onSuccess: () => { onRecorded(); setDecisionReason(""); } });
  return <section className="border border-[#d8d1c4] bg-[#f7f5f0] p-4"><div className="flex items-start gap-2"><ShieldCheck size={16} className="mt-0.5 text-[#a46c18]" /><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#a46c18]">Eligibility decision</p><p className="mt-1 text-[11px] leading-5 text-gray-600">Record an administrator decision. An active policy can be snapshotted here, but it does not create an automatic clearance or decline.</p></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-semibold text-gray-600">Decision<select value={status} onChange={event => setStatus(event.target.value as typeof status)} className="mt-1 h-9 w-full border border-gray-300 bg-white px-2 text-xs text-black"><option value="manual_review">Manual review</option><option value="cleared">Cleared after review</option><option value="unable_to_proceed">Unable to proceed</option></select></label><label className="text-[10px] font-semibold text-gray-600">Active policy snapshot (optional)<select value={eligibilityPolicyId} onChange={event => setEligibilityPolicyId(event.target.value)} className="mt-1 h-9 w-full border border-gray-300 bg-white px-2 text-xs text-black"><option value="">No policy snapshot</option>{applicablePolicies.map(policy => <option key={policy.id} value={String(policy.id)}>{policy.code} · v{policy.version}</option>)}</select></label></div><label className="mt-3 block text-[10px] font-semibold text-gray-600">Decision rationale<textarea value={decisionReason} onChange={event => setDecisionReason(event.target.value)} rows={3} placeholder="Record the review basis without adding sensitive license, biometric, or payment details." className="mt-1 w-full border border-gray-300 bg-white p-2 text-xs font-normal leading-5 text-black" /></label><button type="button" disabled={decisionReason.trim().length < 3 || review.isPending} onClick={() => review.mutate({ reference, status, decisionReason, eligibilityPolicyId: eligibilityPolicyId ? Number(eligibilityPolicyId) : undefined })} className="mt-3 h-9 bg-black px-3 text-[10px] font-bold text-white disabled:opacity-50">{review.isPending ? "Recording…" : "Record eligibility decision"}</button>{review.error && <p className="mt-2 text-[10px] text-red-600">{review.error.message}</p>}</section>;
}
