import { useState } from "react";
import { AlertTriangle } from "lucide-react";
import { trpc } from "@/lib/trpc";

type AssignedVehicle = { id: number; vehicleName: string };

export function FleetPartnerIncidentReporter({ vehicles }: { vehicles: AssignedVehicle[] }) {
  const utils = trpc.useUtils();
  const report = trpc.fleetPartner.reportIncident.useMutation({ onSuccess: () => { setDescription(""); setLocation(""); void utils.fleetPartner.overview.invalidate(); } });
  const [vehiclePassportId, setVehiclePassportId] = useState("");
  const [incidentType, setIncidentType] = useState<"mechanical" | "damage" | "theft" | "towing" | "ticket_or_impound" | "roadside" | "other">("mechanical");
  const [severity, setSeverity] = useState<"standard" | "urgent">("standard");
  const [location, setLocation] = useState("");
  const [description, setDescription] = useState("");
  if (!vehicles.length) return null;
  return <section className="border-t border-gray-200 pt-8"><article className="border border-[#e7d8b5] bg-[#fffaf0] p-6"><p className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-[#a8832d]"><AlertTriangle className="h-4 w-4" />Assigned vehicle issue</p><h3 className="mt-2 font-display text-2xl font-bold text-black">Report a vehicle incident</h3><p className="mt-2 max-w-3xl text-xs leading-5 text-gray-600">Report an issue for an assigned Vehicle Passport. DreamCarz operations reviews the record; this does not expose customer or transaction details, change vehicle readiness, or create a payment decision.</p><div className="mt-5 grid gap-3 lg:grid-cols-2"><select value={vehiclePassportId} onChange={event => setVehiclePassportId(event.target.value)} className="h-10 border border-gray-300 bg-white px-3 text-sm text-black"><option value="">Select an assigned vehicle</option>{vehicles.map(vehicle => <option key={vehicle.id} value={vehicle.id}>{vehicle.vehicleName}</option>)}</select><div className="grid grid-cols-2 gap-3"><select value={incidentType} onChange={event => setIncidentType(event.target.value as typeof incidentType)} className="h-10 border border-gray-300 bg-white px-3 text-sm text-black"><option value="mechanical">Mechanical</option><option value="damage">Damage</option><option value="theft">Theft</option><option value="towing">Towing</option><option value="ticket_or_impound">Ticket or impound</option><option value="roadside">Roadside</option><option value="other">Other</option></select><select value={severity} onChange={event => setSeverity(event.target.value as typeof severity)} className="h-10 border border-gray-300 bg-white px-3 text-sm text-black"><option value="standard">Standard</option><option value="urgent">Urgent</option></select></div><input value={location} onChange={event => setLocation(event.target.value)} placeholder="Reported location (optional)" className="h-10 border border-gray-300 px-3 text-sm text-black" /><textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Describe the vehicle issue for operations" className="min-h-[78px] border border-gray-300 p-3 text-sm text-black" /></div><button type="button" disabled={!vehiclePassportId || description.trim().length < 8 || report.isPending} onClick={() => report.mutate({ vehiclePassportId: Number(vehiclePassportId), incidentType, severity, description: description.trim(), reportedLocation: location.trim() || undefined })} className="mt-3 h-10 bg-black px-4 text-xs font-bold text-white disabled:opacity-50">{report.isPending ? "Reporting…" : "Report to operations"}</button>{report.error && <p className="mt-2 text-xs text-red-600">{report.error.message}</p>}</article></section>;
}
