import { useMemo, useState } from "react";
import { Link2, PauseCircle, PlayCircle, UserRoundCheck, XCircle } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function FleetPartnerAssignmentManager() {
  const overview = trpc.fleetPartner.adminAssignmentOverview.useQuery(undefined, { refetchOnWindowFocus: false });
  const utils = trpc.useUtils();
  const [partnerUserId, setPartnerUserId] = useState("");
  const [vehiclePassportId, setVehiclePassportId] = useState("");
  const assign = trpc.fleetPartner.assignVehicle.useMutation({ onSuccess: () => { setVehiclePassportId(""); void utils.fleetPartner.adminAssignmentOverview.invalidate(); } });
  const updateAccess = trpc.fleetPartner.updateVehicleAssignment.useMutation({ onSuccess: () => void utils.fleetPartner.adminAssignmentOverview.invalidate() });
  const partnerNames = useMemo(() => new Map((overview.data?.partners ?? []).map(partner => [partner.userId, partner.businessName || `Partner account #${partner.userId}`])), [overview.data?.partners]);
  const passportNames = useMemo(() => new Map((overview.data?.passports ?? []).map(passport => [passport.id, passport.vehicleName])), [overview.data?.passports]);

  return <section className="border border-[#ded8cf] bg-[#faf9f6] p-5 sm:p-6">
    <div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center bg-black text-[#d3a934]"><UserRoundCheck size={16} /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#a8832d]">Fleet Partner controls</p><h3 className="mt-1 text-[16px] font-bold text-black">Vehicle Passport assignments</h3><p className="mt-1 max-w-3xl text-[12px] leading-5 text-gray-500">Grant, pause, or end access only for active Fleet Partner profiles with the required role. These controls do not share customer, pricing, payment, or document records and do not change vehicle readiness.</p></div></div>
    <div className="mt-5 grid gap-3 border border-gray-200 bg-white p-4 lg:grid-cols-[1fr_1fr_auto]">
      <label className="text-[10px] font-bold uppercase tracking-wide text-gray-500">Active Fleet Partner<select value={partnerUserId} onChange={event => setPartnerUserId(event.target.value)} className="mt-1 h-10 w-full border border-gray-300 bg-white px-3 text-[12px] font-medium text-black"><option value="">Select a partner profile</option>{overview.data?.partners.map(partner => <option key={partner.userId} value={partner.userId}>{partner.businessName || `Partner account #${partner.userId}`}</option>)}</select></label>
      <label className="text-[10px] font-bold uppercase tracking-wide text-gray-500">Vehicle Passport<select value={vehiclePassportId} onChange={event => setVehiclePassportId(event.target.value)} className="mt-1 h-10 w-full border border-gray-300 bg-white px-3 text-[12px] font-medium text-black"><option value="">Select a Vehicle Passport</option>{overview.data?.passports.map(passport => <option key={passport.id} value={passport.id}>{passport.vehicleName} · {passport.readinessStatus.replaceAll("_", " ")}</option>)}</select></label>
      <div className="flex items-end"><button type="button" disabled={!partnerUserId || !vehiclePassportId || assign.isPending} onClick={() => assign.mutate({ partnerUserId: Number(partnerUserId), vehiclePassportId: Number(vehiclePassportId) })} className="inline-flex h-10 w-full items-center justify-center gap-2 bg-black px-4 text-[11px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"><Link2 size={13} />{assign.isPending ? "Assigning…" : "Assign vehicle"}</button></div>
    </div>
    {assign.error && <p className="mt-3 text-[11px] text-red-600">{assign.error.message}</p>}
    <div className="mt-4 overflow-x-auto border border-gray-200 bg-white"><table className="min-w-[680px] w-full text-left"><thead className="border-b border-gray-200 bg-[#f4f1eb]"><tr className="text-[10px] uppercase tracking-wide text-gray-500"><th className="px-4 py-3">Fleet Partner</th><th className="px-4 py-3">Vehicle Passport</th><th className="px-4 py-3">Access</th><th className="px-4 py-3">Assigned</th><th className="px-4 py-3"></th></tr></thead><tbody>{overview.data?.assignments.map(assignment => <tr key={assignment.id} className="border-b border-gray-100 last:border-0"><td className="px-4 py-3 text-[11px] font-semibold text-black">{partnerNames.get(assignment.partnerUserId) || "Partner profile no longer active"}</td><td className="px-4 py-3 text-[11px] text-gray-700">{passportNames.get(assignment.vehiclePassportId) || "Vehicle Passport unavailable"}</td><td className="px-4 py-3"><span className="border border-gray-300 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-gray-600">{assignment.accessStatus}</span></td><td className="px-4 py-3 text-[10px] text-gray-500">{new Date(assignment.assignedAt).toLocaleDateString()}</td><td className="px-4 py-3"><div className="flex gap-2">{assignment.accessStatus !== "active" && <button type="button" onClick={() => updateAccess.mutate({ assignmentId: assignment.id, accessStatus: "active" })} disabled={updateAccess.isPending} className="inline-flex items-center gap-1 text-[10px] font-bold text-black underline underline-offset-4"><PlayCircle size={12} />Activate</button>}{assignment.accessStatus === "active" && <button type="button" onClick={() => updateAccess.mutate({ assignmentId: assignment.id, accessStatus: "paused" })} disabled={updateAccess.isPending} className="inline-flex items-center gap-1 text-[10px] font-bold text-[#8a6710] underline underline-offset-4"><PauseCircle size={12} />Pause</button>}{assignment.accessStatus !== "ended" && <button type="button" onClick={() => updateAccess.mutate({ assignmentId: assignment.id, accessStatus: "ended" })} disabled={updateAccess.isPending} className="inline-flex items-center gap-1 text-[10px] font-bold text-gray-600 underline underline-offset-4"><XCircle size={12} />End</button>}</div></td></tr>)}{!overview.isLoading && !overview.data?.assignments.length && <tr><td colSpan={5} className="px-4 py-5 text-[11px] text-gray-400">No Fleet Partner Vehicle Passport assignments have been recorded.</td></tr>}</tbody></table></div>
    {overview.error || updateAccess.error ? <p className="mt-3 text-[11px] text-red-600">{overview.error?.message || updateAccess.error?.message}</p> : null}
  </section>;
}
