import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, CircleDashed, RefreshCw } from "lucide-react";

const stateStyle = {
  blocker: { label: "Blocked", className: "border-red-200 bg-red-50 text-red-700", icon: AlertTriangle },
  attention: { label: "Needs review", className: "border-amber-200 bg-amber-50 text-amber-800", icon: CircleDashed },
  ready: { label: "Tracked", className: "border-emerald-200 bg-emerald-50 text-emerald-700", icon: CheckCircle2 },
} as const;

export function LaunchReadiness() {
  const readiness = trpc.operations.launchReadiness.useQuery(undefined, { refetchOnWindowFocus: false });
  const result = readiness.data;

  return <section className="border border-[#ded8cf] bg-[#faf9f6] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#B8860B]">Launch governance</p><h3 className="mt-1 text-[17px] font-bold text-black">Launch readiness</h3><p className="mt-1 max-w-3xl text-[12px] leading-5 text-gray-500">A live operational review of recorded readiness signals. This is not a legal, financial, security, or launch approval.</p></div><button type="button" onClick={() => readiness.refetch()} disabled={readiness.isFetching} className="inline-flex h-9 items-center gap-2 border border-gray-300 bg-white px-3 text-[11px] font-semibold text-black disabled:opacity-50"><RefreshCw size={13} className={readiness.isFetching ? "animate-spin" : ""} />Refresh</button></div>{readiness.isLoading && <p className="py-6 text-center text-[12px] text-gray-400">Loading readiness signals…</p>}{readiness.error && <p className="mt-4 text-[12px] text-red-600">{readiness.error.message}</p>}{result && <><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{result.checks.map(check => { const status = stateStyle[check.state]; const Icon = status.icon; return <article key={check.key} className="border border-gray-200 bg-white p-4"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-bold text-black">{check.label}</p><span className={`inline-flex items-center gap-1 border px-2 py-1 text-[9px] font-bold uppercase tracking-wide ${status.className}`}><Icon size={10} />{status.label}</span></div><p className="mt-3 text-[11px] leading-5 text-gray-600">{check.detail}</p></article>; })}</div><p className="mt-4 text-[10px] leading-5 text-gray-500">Recorded {new Date(result.generatedAt).toLocaleString()}. Current record counts: {result.summary.transactionCount} transactions, {result.summary.approvedQuoteCount} approved quotes, {result.summary.pendingIdentityCount} identity reviews, {result.summary.pendingPaymentCount} payment reviews, and {result.summary.pendingAgreementCount} agreement reviews. AWS server credentials: {result.summary.awsFaceLiveness.serverCredentialsConfigured ? "configured" : "not configured"}; temporary browser credential path: {result.summary.awsFaceLiveness.browserCredentialBrokerConfigured ? "prepared" : "not configured"}; customer camera flow: {result.summary.awsFaceLiveness.browserFlowEnabled ? "enabled" : "disabled"}.</p></>}</section>;
}
