import { useState } from "react";
import { ClipboardCheck, Wrench } from "lucide-react";
import { trpc } from "@/lib/trpc";

const inputClass = "mt-1 h-10 w-full border border-gray-300 bg-white px-3 text-xs text-black outline-none focus:border-black";
const emptyForm = { vehicleId: "", vehicleName: "", acquisitionStatus: "not_recorded" as const, readinessStatus: "not_ready" as const, stockNumber: "", vinLast4: "", currentLocation: "", currentOdometer: "", fuelOrChargeLevel: "", notes: "" };

export function VehiclePassportManager() {
  const utils = trpc.useUtils();
  const passports = trpc.operations.vehiclePassports.list.useQuery(undefined, { refetchOnWindowFocus: false });
  const [form, setForm] = useState(emptyForm);
  const save = trpc.operations.vehiclePassports.save.useMutation({ onSuccess: () => { passports.refetch(); setForm(emptyForm); } });

  const submit = () => save.mutate({
    vehicleId: form.vehicleId.trim(), vehicleName: form.vehicleName.trim(), acquisitionStatus: form.acquisitionStatus, readinessStatus: form.readinessStatus,
    stockNumber: form.stockNumber.trim() || undefined, vinLast4: form.vinLast4.trim() || undefined, currentLocation: form.currentLocation.trim() || undefined,
    currentOdometer: form.currentOdometer.trim() ? Number(form.currentOdometer) : undefined, fuelOrChargeLevel: form.fuelOrChargeLevel.trim() || undefined, notes: form.notes.trim() || undefined,
  });

  return <section className="mt-6 border border-[#ded8cf] bg-[#faf9f6] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#B8860B]">Fleet operations</p><h3 className="mt-1 text-[16px] font-bold text-black">Vehicle Passports</h3><p className="mt-1 max-w-3xl text-[12px] leading-5 text-gray-500">Create protected operating records for confirmed inventory. VIN, plate, insurance, and acquisition details are never published to the public fleet.</p></div><span className="inline-flex items-center gap-2 border border-gray-200 bg-white px-3 py-2 text-[11px] font-semibold text-gray-600"><ClipboardCheck size={14} className="text-[#B8860B]" /> {passports.data?.length ?? 0} records</span></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[11px] font-semibold text-gray-600">Internal vehicle ID<input value={form.vehicleId} onChange={event => setForm(current => ({ ...current, vehicleId: event.target.value }))} placeholder="e.g., 2024-chevrolet-malibu-gray" className={inputClass} /></label><label className="text-[11px] font-semibold text-gray-600">Vehicle name<input value={form.vehicleName} onChange={event => setForm(current => ({ ...current, vehicleName: event.target.value }))} placeholder="2024 Chevrolet Malibu · Gray" className={inputClass} /></label><label className="text-[11px] font-semibold text-gray-600">Acquisition<select value={form.acquisitionStatus} onChange={event => setForm(current => ({ ...current, acquisitionStatus: event.target.value as typeof form.acquisitionStatus }))} className={inputClass}><option value="not_recorded">Not recorded</option><option value="owned">Owned</option><option value="leased">Leased</option><option value="partner_managed">Partner managed</option><option value="retired">Retired</option></select></label><label className="text-[11px] font-semibold text-gray-600">Readiness<select value={form.readinessStatus} onChange={event => setForm(current => ({ ...current, readinessStatus: event.target.value as typeof form.readinessStatus }))} className={inputClass}><option value="not_ready">Not ready</option><option value="inspection_due">Inspection due</option><option value="maintenance_due">Maintenance due</option><option value="available">Available</option><option value="reserved">Reserved</option><option value="active_rental">Active rental</option><option value="out_of_service">Out of service</option><option value="retired">Retired</option></select></label></div>
    <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[11px] font-semibold text-gray-600">Stock number<input value={form.stockNumber} onChange={event => setForm(current => ({ ...current, stockNumber: event.target.value }))} className={inputClass} /></label><label className="text-[11px] font-semibold text-gray-600">VIN last four<input value={form.vinLast4} onChange={event => setForm(current => ({ ...current, vinLast4: event.target.value.toUpperCase() }))} maxLength={4} className={inputClass} /></label><label className="text-[11px] font-semibold text-gray-600">Current location<input value={form.currentLocation} onChange={event => setForm(current => ({ ...current, currentLocation: event.target.value }))} className={inputClass} /></label><label className="text-[11px] font-semibold text-gray-600">Odometer<input value={form.currentOdometer} onChange={event => setForm(current => ({ ...current, currentOdometer: event.target.value }))} min="0" type="number" className={inputClass} /></label></div>
    <div className="mt-3 grid gap-3 sm:grid-cols-[0.7fr_1.3fr]"><label className="text-[11px] font-semibold text-gray-600">Fuel or charge<input value={form.fuelOrChargeLevel} onChange={event => setForm(current => ({ ...current, fuelOrChargeLevel: event.target.value }))} placeholder="e.g., 3/4 fuel" className={inputClass} /></label><label className="text-[11px] font-semibold text-gray-600">Internal notes<textarea value={form.notes} onChange={event => setForm(current => ({ ...current, notes: event.target.value }))} rows={2} className="mt-1 w-full border border-gray-300 bg-white p-3 text-xs text-black outline-none focus:border-black" /></label></div>
    <button type="button" disabled={save.isPending || form.vehicleId.trim().length < 2 || form.vehicleName.trim().length < 2} onClick={submit} className="mt-4 inline-flex h-10 items-center gap-2 bg-black px-4 text-xs font-semibold text-white disabled:opacity-50"><Wrench size={14} /> {save.isPending ? "Saving record…" : "Save Vehicle Passport"}</button>{save.error ? <p className="mt-2 text-xs text-red-600">{save.error.message}</p> : null}
    <div className="mt-5 overflow-x-auto border border-gray-200 bg-white"><table className="min-w-[760px] w-full text-left"><thead className="border-b border-gray-200 bg-[#f4f1eb]"><tr className="text-[10px] uppercase tracking-wider text-gray-500"><th className="px-3 py-3">Vehicle</th><th className="px-3 py-3">Readiness</th><th className="px-3 py-3">Location</th><th className="px-3 py-3">Odometer</th><th className="px-3 py-3">Updated</th></tr></thead><tbody>{passports.data?.map(passport => <tr key={passport.id} className="border-b border-gray-100 last:border-0 text-[11px] text-gray-600"><td className="px-3 py-3"><p className="font-semibold text-black">{passport.vehicleName}</p><p className="mt-0.5 text-[10px] text-gray-400">{passport.vehicleId} · VIN ••••{passport.vinLast4 || "—"}</p></td><td className="px-3 py-3 capitalize">{passport.readinessStatus.replaceAll("_", " ")}</td><td className="px-3 py-3">{passport.currentLocation || "Not recorded"}</td><td className="px-3 py-3">{passport.currentOdometer ?? "Not recorded"}</td><td className="px-3 py-3">{new Date(passport.updatedAt).toLocaleDateString()}</td></tr>)}{!passports.isLoading && !passports.data?.length ? <tr><td colSpan={5} className="px-3 py-8 text-center text-[11px] text-gray-400">No Vehicle Passports have been created. Create records only for confirmed inventory.</td></tr> : null}</tbody></table></div>
  </section>;
}
